---        
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wt-demo-app-east-e101
  namespace: default
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: ecs-demo-co-apps
  path: ./sites/east-site/wt-monitoring-app/turbine-e101
  prune: true
  timeout: 1m

---        
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wt-demo-app-base
  namespace: default
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: ecs-demo-co-apps
  path: ./base/wt-monitoring-app
  prune: true
  timeout: 1m


