apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ecs-demo-co-infra
  namespace: default
spec:
  interval: 1m
  url: https://github.com/kmikholap/ecs-demo-co-infra.git
  ref:
    branch: main

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ecs-demo-co-apps
  namespace: default
spec:
  interval: 1m
  url: https://github.com/kmikholap/ecs-demo-co-apps.git
  ref:
    branch: main

---        
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wt-demo-app-base
  namespace: default
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: ecs-demo-co-apps
  path: ./base/wt-monitoring-app
  prune: true
  timeout: 1m


---        
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wt-demo-app-east-e101
  namespace: default
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: ecs-demo-co-apps
  path: ./sites/east-site/wt-monitoring-app/turbine-e101
  prune: true
  timeout: 1m
  dependsOn:
    - name: wt-demo-app-base
  patches:
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/env/0/valueFrom/configMapKeyRef/name
          value: backend-us-east-site-01-e101
        - op: replace
          path: /spec/template/spec/containers/0/env/1/valueFrom/configMapKeyRef/name
          value: backend-us-east-site-01-e101
        - op: replace
          path: /spec/template/spec/containers/0/env/2/valueFrom/configMapKeyRef/name
          value: backend-us-east-site-01-e101
      target:
        kind: Deployment
        name: backend-api
        namespace: default






