apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wt-demo-apps
  namespace: default
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: ecs-demo-co-apps
  path: ./sites/east-site/wt-monitoring-app/turbine-e101
  prune: true
  timeout: 1m